#!/usr/bin/env python3
"""Regenerate VAULT_MAP.md from vault state.

Deterministic — same inputs produce same output. Run from vault root or pass --root.
Designed to be invoked by the morning-review routine; safe to run by hand.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

FOLDER_DESCRIPTIONS = {
    "Inbox": "Quick captures awaiting triage",
    "Tasks": "Actionable task files",
    "Logs": "Daily activity logs",
    "Personal": "Personal notes",
    "Notes": "Reference notes on active projects",
    "Work": "Project context + per-project agent session notes",
    "Literature": "Paper knowledge base — see Literature/INDEX",
    "docs": "Specs, plans, supporting docs",
}

PROJECT_HEADER_RE = re.compile(r"^##\s+Active Project:\s+(.+?)\s*$")
FIELD_RE = re.compile(r"^-\s+\*\*(Status|Last session|Next)[:*]+\*\*\s*(.*?)\s*$")


def count_markdown(root: Path, folder: str) -> int:
    p = root / folder
    if not p.is_dir():
        return 0
    return sum(1 for _ in p.rglob("*.md"))


def parse_context(context_path: Path) -> list[dict]:
    if not context_path.is_file():
        return []
    projects: list[dict] = []
    current: dict | None = None
    for raw in context_path.read_text(encoding="utf-8").splitlines():
        m = PROJECT_HEADER_RE.match(raw)
        if m:
            if current:
                projects.append(current)
            current = {"name": m.group(1), "Status": "", "Last session": "", "Next": ""}
            continue
        if current:
            fm = FIELD_RE.match(raw)
            if fm:
                current[fm.group(1)] = fm.group(2)
    if current:
        projects.append(current)
    return projects


def find_readme(root: Path, project_name: str) -> str | None:
    """Best-effort link to Work/ClaudeCode/<dir>/README based on project name."""
    cc = root / "Work" / "ClaudeCode"
    if not cc.is_dir():
        return None
    target = project_name.lower().replace(" ", "_").replace("-", "_")
    for child in cc.iterdir():
        if not child.is_dir():
            continue
        norm = child.name.lower().replace("-", "_")
        if norm == target or norm == project_name.lower():
            return f"Work/ClaudeCode/{child.name}/README"
    return None


def recent_commits(root: Path, limit: int = 15) -> list[tuple[str, str, str]]:
    """Return (date, short-hash, subject) for last `limit` commits touching .md files."""
    try:
        out = subprocess.check_output(
            [
                "git", "-C", str(root), "log",
                f"-{limit}",
                "--pretty=format:%ad\x1f%h\x1f%s",
                "--date=short",
                "--", "*.md",
            ],
            text=True,
        )
    except subprocess.CalledProcessError:
        return []
    rows = []
    for line in out.splitlines():
        if not line.strip():
            continue
        parts = line.split("\x1f")
        if len(parts) == 3:
            rows.append(tuple(parts))  # type: ignore[arg-type]
    return rows


def render(root: Path) -> str:
    today = dt.date.today().isoformat()
    lines: list[str] = []
    lines.append("# Vault Map")
    lines.append("")
    lines.append(f"_Auto-generated by `scripts/build-vault-map.py`. Do not edit by hand. Last updated: {today}_")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Structure
    lines.append("## Structure")
    lines.append("")
    lines.append("| Folder | Markdown files | Description |")
    lines.append("|--------|----------------|-------------|")
    total = 0
    for folder, desc in FOLDER_DESCRIPTIONS.items():
        n = count_markdown(root, folder)
        total += n
        if (root / folder).is_dir():
            lines.append(f"| [[{folder}/]] | {n} | {desc} |")
    lines.append("")
    lines.append(f"**Total markdown files:** {total}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Projects from context.md
    lines.append("## Active Projects")
    lines.append("")
    lines.append("_Parsed from `Work/context.md`. To change project status, edit that file._")
    lines.append("")
    projects = parse_context(root / "Work" / "context.md")
    if not projects:
        lines.append("_No projects found in Work/context.md._")
    else:
        for p in projects:
            lines.append(f"### {p['name']}")
            if p.get("Status"):
                lines.append(f"- **Status:** {p['Status']}")
            if p.get("Last session"):
                lines.append(f"- **Last session:** {p['Last session']}")
            if p.get("Next"):
                lines.append(f"- **Next:** {p['Next']}")
            readme = find_readme(root, p["name"])
            if readme:
                lines.append(f"- **README:** [[{readme}]]")
            lines.append("")
    lines.append("---")
    lines.append("")

    # Recent commits
    lines.append("## Recent Activity")
    lines.append("")
    lines.append("Last 15 commits touching markdown files.")
    lines.append("")
    lines.append("| Date | Commit | Subject |")
    lines.append("|------|--------|---------|")
    for date, h, subj in recent_commits(root):
        subj_safe = subj.replace("|", "\\|")
        lines.append(f"| {date} | `{h}` | {subj_safe} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Literature pointer
    lines.append("## Literature")
    lines.append("")
    lines.append("Paper knowledge base lives in [[Literature/INDEX]].")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", help="Vault root (default: cwd)")
    ap.add_argument("--check", action="store_true", help="Exit 1 if VAULT_MAP.md would change")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    out_path = root / "VAULT_MAP.md"
    new = render(root)
    old = out_path.read_text(encoding="utf-8") if out_path.is_file() else ""

    if args.check:
        if new != old:
            print("VAULT_MAP.md is out of date", file=sys.stderr)
            return 1
        return 0

    if new != old:
        out_path.write_text(new, encoding="utf-8")
        print(f"wrote {out_path.relative_to(root)}")
    else:
        print("VAULT_MAP.md unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
